install.packages("dplyr")
library(dplyr)
library(plyr)
library(GGally)
library(ggplot2)
setwd("~/Downloads")
#DATA PREPROCESSING
data <- read.csv("Telco.csv")
View(data)
str(data)
summary(data)
sapply(data, function(x) sum(is.na(x)))
data$TotalCharges=ifelse(is.na(data$TotalCharges),ave(data$TotalCharges,FUN=function(x) mean(x, na.rm=TRUE)),data$TotalCharges)
sapply(data, function(x) sum(is.na(x)))

sapply(data, function(x) length(unique(x)))
unique(data[c("gender")])
table(data$gender)
unique(data[c("SeniorCitizen")])
table(data$SeniorCitizen)
unique(data[c("Partner")])
table(data$Partner)
unique(data[c("Dependents")])
table(data$Dependents)
unique(data[c("MultipleLines")])
table(data$MultipleLines)
unique(data[c("PhoneService")])
table(data$PhoneService)
unique(data[c("InternetService")])
table(data$InternetService)
unique(data[c("OnlineSecurity")])
table(data$OnlineSecurity)
unique(data[c("OnlineBackup")])
table(data$OnlineBackup)
unique(data[c("DeviceProtection")])
table(data$DeviceProtection)
unique(data[c("TechSupport")])
table(data$TechSupport)
unique(data[c("StreamingTV")])
table(data$StreamingTV)
unique(data[c("StreamingMovies")])
table(data$StreamingMovies)
unique(data[c("Contract")])
table(data$Contract)
unique(data[c("PaperlessBilling")])
table(data$PaperlessBilling)
unique(data[c("PaymentMethod")])
table(data$PaymentMethod)
unique(data[c("Churn")])
table(data$Churn)

data$Partner = factor(data$Partner, levels = c('Yes', 'No'), labels = c(1, 0))
data$Dependents = factor(data$Dependents, levels = c('Yes', 'No'), labels = c(1, 0))
data$PhoneService = factor(data$PhoneService, levels = c('Yes', 'No'), labels = c(1, 0))
data$OnlineSecurity = factor(data$OnlineSecurity, levels = c('Yes', 'No'), labels = c(1, 0))
data$OnlineBackup = factor(data$OnlineBackup, levels = c('Yes', 'No'), labels = c(1, 0))
data$DeviceProtection = factor(data$DeviceProtection, levels = c('Yes', 'No'), labels = c(1, 0))
data$TechSupport = factor(data$TechSupport, levels = c('Yes', 'No'), labels = c(1, 0))
data$StreamingTV = factor(data$StreamingTV, levels = c('Yes', 'No'), labels = c(1, 0))
data$StreamingMovies = factor(data$StreamingMovies, levels = c('Yes', 'No'), labels = c(1, 0))
data$PaperlessBilling = factor(data$PaperlessBilling, levels = c('Yes', 'No'), labels = c(1, 0))
data$Churn = factor(data$Churn, levels = c('Yes', 'No'), labels = c(1, 0))

data$Partner <- as.integer(as.character(data$Partner))  
data$Dependents <- as.integer(as.character(data$Dependents))  
data$PhoneService <- as.integer(as.character(data$PhoneService))  
data$OnlineSecurity <- as.integer(as.character(data$OnlineSecurity))  
data$OnlineBackup <- as.integer(as.character(data$OnlineBackup))  
data$DeviceProtection <- as.integer(as.character(data$DeviceProtection))  
data$TechSupport <- as.integer(as.character(data$TechSupport))  
data$StreamingTV <- as.integer(as.character(data$StreamingTV))  
data$StreamingMovies <- as.integer(as.character(data$StreamingMovies))  
data$PaperlessBilling <- as.integer(as.character(data$PaperlessBilling))  
data$Churn <- as.integer(as.character(data$Churn))  

str(data)
sapply(data, function(x) sum(is.na(x)))
sapply(data, function(x) sum(is.na(x)))
data$OnlineSecurity=ifelse(is.na(data$OnlineSecurity),ave(data$OnlineSecurity,FUN=function(x) mean(x, na.rm=TRUE)),data$OnlineSecurity)
data$OnlineBackup=ifelse(is.na(data$OnlineBackup),ave(data$OnlineBackup,FUN=function(x) mean(x, na.rm=TRUE)),data$OnlineBackup)
data$DeviceProtection=ifelse(is.na(data$DeviceProtection),ave(data$DeviceProtection,FUN=function(x) mean(x, na.rm=TRUE)),data$DeviceProtection)
data$TechSupport=ifelse(is.na(data$TechSupport),ave(data$TechSupport,FUN=function(x) mean(x, na.rm=TRUE)),data$TechSupport)
data$StreamingTV=ifelse(is.na(data$StreamingTV),ave(data$StreamingTV,FUN=function(x) mean(x, na.rm=TRUE)),data$StreamingTV)
data$StreamingMovies=ifelse(is.na(data$StreamingMovies),ave(data$StreamingMovies,FUN=function(x) mean(x, na.rm=TRUE)),data$StreamingMovies)
sapply(data, function(x) sum(is.na(x)))

data$MultipleLines <- as.factor(mapvalues(data$MultipleLines,from=c("No phone service"),to=c("No")))
data$MultipleLines = factor(data$MultipleLines, levels = c('Yes', 'No'), labels = c(1, 0))
data$MultipleLines <- as.integer(as.character(data$MultipleLines)) 

data$customerID <- NULL
min(data$tenure)
max(data$tenure)

boxplot(data$tenure,main="Boxplot of tenure",xlab="Tenure")
boxplot(data$MonthlyCharges,main="Boxplot of Monthly Charges",xlab="Monthly Charges")
ggplot(data, aes(x = Churn))+ geom_histogram(stat = "count", fill = c("sky blue", "orange"))
hist(data$tenure,main="Distribution of tenure",xlab="Tenure",xlim=c(0,80),col="blue",breaks=8)
hist(data$TotalCharges,main="Distribution of total charges",xlab="Total Charges",xlim=c(0,10000),col="red",breaks=9)
hist(data$MonthlyCharges,main="Distribution of monthly charges",xlab="Monthly Charges",xlim=c(0,120),col="green",breaks=11)
ggplot(data=data, mapping=aes(x=TotalCharges, y=tenure)) + geom_point()
ggplot(data, aes(x="", y=Churn, fill=InternetService))+geom_bar(stat = "identity")+coord_polar("y")
ggplot(data, aes(x="", y=Churn, fill=PaymentMethod))+geom_bar(stat = "identity")+coord_polar("y")
ggplot(data, aes(x="", y=Churn, fill=Contract))+geom_bar(stat = "identity")+coord_polar("y")

#Correlation
ggcorr(data)

#Regression Analysis

#logistic regression

newdata <- select(data,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,PaperlessBilling,MonthlyCharges,TotalCharges,Churn)
View(newdata)

install.packages("caTools")
library(caTools)
split <- sample.split(data,SplitRatio=0.8)
split
training <- subset(data,split=="TRUE")
testing <- subset(data,split=="FALSE")
model <- glm(Churn~.,training,family="binomial")
summary(model)
anova(model, test="Chisq")

testing$Churn <- as.character(testing$Churn)
testing$Churn[testing$Churn=="No"] <- "0"
testing$Churn[testing$Churn=="Yes"] <- "1"
fitted.results <- predict(model,newdata=testing,type='response')
fitted.results <- ifelse(fitted.results > 0.5,1,0)
misClasificError <- mean(fitted.results != testing$Churn)
print(paste('Logistic Regression Accuracy',1-misClasificError))
print("Confusion Matrix for Logistic Regression")
table(testing$Churn, fitted.results > 0.5)


#Decision Tree
install.packages("party")
library(party)
tree <- ctree(Churn~tenure+PaperlessBilling, training)
plot(tree)

